import Head from "next/head";
import styles from "../styles/Home.module.css";
import { ToastContainer, toast } from "react-toastify";
import { useAuth } from "../lib/authContext";
import Login from "../pages/login";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const { user } = useAuth();
  const router = useRouter();
  const [loading, setLoading] = useState(true);

  function goToComps() {
    router.push("/comps");
  }

  useEffect(() => {
    if (user && user.emailVerified) {
      toast.success(`Welcome ${user.displayName || "User"}`);
    } else {
      setLoading(false);
    }
  }, [user]);

  useEffect(() => {
    const timer = setTimeout(() => {
      setLoading(false);
    }, 1000);
    return () => clearTimeout(timer);
  }, []);

  return (
    <>
      <Head>
        <title>Learn with Cod - Programming</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {loading && (
        <div className={styles.loadingOverlay}>
          <div className={styles.loadingSpinner}></div>
          <p>Please wait...</p>
        </div>
      )}

      <div className={styles.container}>
        {!loading && user ? goToComps() : <Login />}
      </div>
      <ToastContainer />
    </>
  );
}
