import Head from "next/head";
import Comps from "../pages/comps";
import styles from "../styles/Home.module.css";
import { auth } from "../../firebase.config";
import { useState, useEffect } from "react";

export default function Home() {

  return (
    <>
      <Head>
        <title>Learn with Cod - Programming</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Comps />
      </div>
    </>
  );
}
